# AppVeyor.com is a Continuous Integration service to build and run tests under
# Windows
environment:
  global:
    # SDK v7.0 MSVC Express 2008's SetEnv.cmd script will fail if the
    # /E:ON and /V:ON options are not enabled in the batch script interpreter
    # See: http://stackoverflow.com/a/13751649/163740
    CMD_IN_ENV: "cmd /E:ON /V:ON /C .\\ci_scripts\\appveyor\\run_with_env.cmd"

  matrix:
      - PYTHON: "C:\\Python37-x64"
        PYTHON_VERSION: "3.7.0"
        PYTHON_ARCH: "64"

      - PYTHON: "C:\\Python27-x64"
        PYTHON_VERSION: "2.7.8"
        PYTHON_ARCH: "32"

matrix:
    fast_finish: true

install:
  - "powershell ./ci_scripts/appveyor/install.ps1"
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - "python -m pip install -U pip"

  # Check that we have the expected version and architecture for Python
  - "python --version"
  - "python -c \"import struct; print(struct.calcsize('P') * 8)\""
  - "pip --version"

  - "%CMD_IN_ENV% pip install --timeout=60 numpy pytest wheel"
  - "%CMD_IN_ENV% python setup.py bdist_wheel bdist_wininst"

  - ps: "ls dist"
  #  # build the conda package
  #  - "%CMD_IN_ENV% conda build build_tools/conda-recipe --quiet"
  #
  #  # Move the conda package into the dist directory, to register it
  #  # as an "artifact" for Appveyor. cmd.exe does't have good globbing, so
  #  # we'll use a simple python script.
  #  - python build_tools/move-conda-package.py build_tools/conda-recipe
  #
  #  # Install the generated wheel package to test it
  - "pip install --pre --no-index --find-links dist/ ad3"

# Not a .NET project, we build scikit-learn in the install step instead
build: false

test_script:
  # Change to a non-source folder to make sure we run the tests on the
  # installed library.
  - "echo Running tests"
  - "mkdir empty_folder"
  - "cd empty_folder"

  - "pytest -vs --pyargs ad3"

  # Move back to the project folder
  - "cd .."

  - "echo Running examples"
  - "set NOPLOT=1"
  - "cd examples\\python"
  - "for %%i in (*.py) do (python %%i || exit 1)"

artifacts:
  # Archive the generated wheel package in the ci.appveyor.com build report.
  - path: dist\*

cache:
  - '%APPDATA%\pip\Cache'
